# Generated by Django 5.2.6 on 2025-09-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('job_card_no', models.AutoField(primary_key=True, serialize=False)),
                ('press_no', models.CharField(max_length=20)),
                ('mould_no', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('cust_code', models.CharField(max_length=50)),
                ('material_type', models.CharField(max_length=100)),
                ('size_dimension', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobCardUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('moulder_name', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=50)),
                ('required_qty', models.PositiveIntegerField(default=0)),
                ('received_qty', models.PositiveIntegerField(default=0)),
                ('balance_qty', models.PositiveIntegerField(default=0)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.jobcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
