# Generated by Django 5.2.6 on 2025-09-09 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardupdate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobcardupdate',
            name='moulder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcardupdate',
            name='process',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
