# Generated by Django 5.2.6 on 2025-09-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_worker_remove_jobcard_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='app.worker'),
        ),
    ]
