# Generated by Django 5.2.6 on 2025-09-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobcard_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardupdate',
            name='moulder_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.worker'),
        ),
    ]
