# Generated by Django 5.2.6 on 2025-09-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jobcardupdate_moulder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='press_no',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='required_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcardupdate',
            name='press_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
