# Generated by Django 5.2.6 on 2025-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_jobcard_press_no_jobcard_required_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='timing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
