# Generated by Django 5.2.6 on 2025-09-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jobcard_temperature_jobcard_timing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='timing',
            new_name='time',
        ),
    ]
