# Generated by Django 5.2.6 on 2025-09-15 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_timing_jobcard_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_no', models.CharField(max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.jobcard')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker')),
            ],
        ),
    ]
