# Generated by Django 5.2.6 on 2025-09-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jobcardassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=50)),
                ('size_dimension', models.CharField(max_length=50)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='mould_no',
            field=models.IntegerField(default=0),
        ),
    ]
