# Generated by Django 5.2.6 on 2025-09-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_storeitem_alter_jobcard_mould_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storeitem'),
        ),
    ]
