# Generated by Django 5.2.6 on 2025-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_jobcard_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
