# Generated by Django 5.2.6 on 2025-09-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_jobcard_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='cured_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='foamed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
