# Generated by Django 5.2.6 on 2025-09-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_jobcard_cured_count_jobcard_foamed_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='item_no',
            new_name='item_code',
        ),
    ]
