# Generated by Django 5.2.6 on 2025-10-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_item_no_storeitem_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieRegister',
            fields=[
                ('item_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20)),
                ('od', models.CharField(max_length=20)),
                ('t1', models.CharField(max_length=20)),
                ('t2', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=50)),
                ('die_no', models.CharField(max_length=20)),
                ('new_die', models.CharField(max_length=20)),
                ('curing_temp', models.CharField(max_length=20)),
                ('curing_time', models.CharField(max_length=20)),
            ],
        ),
    ]
