# Generated by Django 5.2.6 on 2025-10-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customer_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='size_dimension',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='added_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='added_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_items', to='app.customer'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='deducted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='deducted_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='die_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='inner_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_items', to='app.material'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='od',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='rack_main',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='rack_sub',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='t1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='t2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
