# Generated by Django 5.2.6 on 2025-10-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add'), ('deduct', 'Deduct')], max_length=10)),
                ('qty', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('previous_stock', models.IntegerField(default=0)),
                ('resulting_stock', models.IntegerField(default=0)),
                ('rack_main', models.CharField(blank=True, max_length=50, null=True)),
                ('rack_sub', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_histories', to='app.customer')),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='app.storeitem')),
            ],
        ),
    ]
