# Generated by Django 5.2.6 on 2025-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_storeitemhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='on_hold', max_length=20),
        ),
    ]
