# Generated by Django 5.2.6 on 2025-10-27 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_purchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_no', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('drawing_no', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_mappings', to='app.customer')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings', to='app.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMappingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, max_length=300, null=True)),
                ('id_val', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID')),
                ('od', models.CharField(blank=True, max_length=50, null=True)),
                ('t1', models.CharField(blank=True, max_length=50, null=True)),
                ('t2', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('die_no', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_qty', models.IntegerField(default=0)),
                ('stock_qty', models.IntegerField(default=0)),
                ('balance_for_production', models.IntegerField(default=0)),
                ('required_qty', models.IntegerField(default=0)),
                ('job_card_no', models.IntegerField(blank=True, null=True)),
                ('job_card_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('die', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dieregister')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.productmapping')),
            ],
        ),
    ]
