# Generated by Django 5.2.6 on 2025-10-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_productmapping_productmappingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardassignment',
            name='job_card',
        ),
        migrations.RemoveField(
            model_name='jobcardupdate',
            name='job_card',
        ),
        migrations.RemoveField(
            model_name='jobcardassignment',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='jobcardupdate',
            name='moulder_name',
        ),
        migrations.RemoveField(
            model_name='jobcardupdate',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobCard',
        ),
        migrations.DeleteModel(
            name='JobCardAssignment',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='JobCardUpdate',
        ),
    ]
