# Generated by Django 5.2.6 on 2025-10-31 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_jobcardassignment_job_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('job_card_no', models.IntegerField(primary_key=True, serialize=False)),
                ('job_card_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('oa_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('id_val', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID')),
                ('od', models.CharField(blank=True, max_length=50, null=True)),
                ('t1', models.CharField(blank=True, max_length=50, null=True)),
                ('t2', models.CharField(blank=True, max_length=50, null=True)),
                ('die_no', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('required_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='app.productmapping')),
                ('pmi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard', to='app.productmappingitem')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('worker_name', models.CharField(blank=True, max_length=120, null=True)),
                ('process', models.CharField(choices=[('foaming', 'Foaming'), ('curing', 'Curing')], max_length=20)),
                ('qty', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='app.jobcard')),
            ],
        ),
    ]
