# Generated by Django 5.2.6 on 2025-11-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_jobcard_jobcardprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmappingitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
