# Generated by Django 5.2.6 on 2025-12-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_productmappingitem_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPendingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.CharField(blank=True, max_length=20, null=True)),
                ('v', models.CharField(blank=True, max_length=20, null=True)),
                ('h', models.CharField(blank=True, max_length=20, null=True)),
                ('urgent', models.CharField(blank=True, max_length=100, null=True)),
                ('despatched', models.CharField(blank=True, max_length=100, null=True)),
                ('despatch_date', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('pending', models.CharField(blank=True, max_length=100, null=True)),
                ('outsource', models.CharField(blank=True, max_length=100, null=True)),
                ('os_ordered_date', models.CharField(blank=True, max_length=50, null=True)),
                ('os_received_date', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_entry', to='app.productmappingitem')),
            ],
        ),
    ]
