# Generated by Django 5.2.6 on 2025-12-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_planningpendingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningpendingentry',
            name='despatched_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
