# Generated by Django 5.2.6 on 2025-12-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_planningpendingentry_despatched_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardprogress',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcardprogress',
            name='temperature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobcardprogress',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
