    # Generated by Django 5.2.6 on 2026-01-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_jobcardprogress_material_jobcardprogress_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningpendingentry',
            name='h',
        ),
        migrations.RemoveField(
            model_name='planningpendingentry',
            name='u',
        ),
        migrations.RemoveField(
            model_name='planningpendingentry',
            name='v',
        ),
    ]
