# Generated by Django 4.2.27 on 2026-01-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pgvector_schema_embedding'),
        ('app', '0030_remove_planningpendingentry_h_and_more'),
    ]

    operations = [
    ]
