# Generated by Django 4.2.27 on 2026-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_chatbotreviewitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemaembedding',
            options={},
        ),
        migrations.RemoveField(
            model_name='schemaembedding',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chatbotreviewitem',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatbotreviewitem',
            name='intent_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotreviewitem',
            name='kind',
            field=models.CharField(default='query', max_length=32),
        ),
        migrations.AddField(
            model_name='chatbotreviewitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotreviewitem',
            name='published_to_intent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbotreviewitem',
            name='qdrant_point_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='schemaembedding',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schemaembedding',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='schemaembedding',
            name='text_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='schemaembedding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schemaembedding',
            name='chunk_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemaembedding',
            name='table_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
